
GET http://localhost:3000/admin/authentification
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJ1c2VybmFtZSI6IkJsZXNzZWQiLCJpYXQiOjE3MTk5MTczODksImV4cCI6MTcxOTk1MzM4OX0.Z-1W9LywWd-1xhIYf9ZTl3u9UNxwnhNpQ9iX5CWLTrk
Admin-Auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJ1c2VybmFtZSI6IkJsZXNzZWQiLCJpYXQiOjE3MTk5MTczODksImV4cCI6MTcxOTk1MzM4OX0.Z-1W9LywWd-1xhIYf9ZTl3u9UNxwnhNpQ9iX5CWLTrk