GET http://localhost:3000/count
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE4OTU1NDE5LCJleHAiOjE3MTg5OTE0MTl9.PRbUZ5abP20sLGXGQGT3ScHIlFNRLbe4fs7a9_u3Xx0