GET http://localhost:3000/count
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzNDY4MzMzLCJleHAiOjE3MTM0NzE5MzN9.atxCI3rBtFJGKCR5ljh89b3G1Tda8Q2vg0D2VaQmYx0