DELETE http://localhost:3000/friends/31/21
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE2NjYyODk5LCJleHAiOjE3MTY2OTg4OTl9.OrCE_a-ApEm5jA7MjISu83JC7rvxJhb8pOj1EuQJjn0