GET http://localhost:3000/friends/user-friends-data/31
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE5MjMwNjYwLCJleHAiOjE3MTkyNjY2NjB9.ndnNQi8EJ-Y9WRprk7X2PRILgyvdsszBJpI0sfXeT4s