GET http://localhost:3000/usergroups/joinusergroups/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzNjE0NDU5LCJleHAiOjE3MTM2MTgwNTl9._TcSceIHNfnHSBLd_VDNSJTfKjDvkwCoAhAXD3tX8lQ