GET http://localhost:3000/messages/unreadMsg/10
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE4OTU3OTEwLCJleHAiOjE3MTg5OTM5MTB9.GNNTOmh1CIE1JuvAyhMGmYVQ62unDhUFUff5u1FYkK0