GET http://localhost:3000/posts/get-comments/3
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE4OTc1MDgxLCJleHAiOjE3MTkwMTEwODF9.l9S-KSi5ogCGzyGUgA5dxU46Knitli-49NLMaHT-2ns