GET http://localhost:3000/users/32
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE4Nzg4OTI3LCJleHAiOjE3MTg4MjQ5Mjd9.aqgbbaGluNfL0QO9S_Wz7FZUqMm5Bbxk_wupFDirGow