GET http://localhost:3000/messages/10/31
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE0NDE2ODM2LCJleHAiOjE3MTQ0MjA0MzZ9.WO6cSdZgRfDvoCqD2MAAbAorHiIwY5eyzW-qmNe-Ddg
