GET http://localhost:3000/messages/unreadMsg/10
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE2MzIyNTMxLCJleHAiOjE3MTYzNTg1MzF9.T5m7VN_55guMS5EZVORG3bcj_4CLV-eL_rO_EZ1PAVw