POST http://localhost:3000/usergroups/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiRGFuaWVsIiwiaWF0IjoxNzEzMzYwNjA2LCJleHAiOjE3MTMzNjQyMDZ9.uvUAuYGbTJkbN9rXL-dBezp330gJNtMFDmLA-kD2bts

{
  "userId" : 3,
  "groupId" : 1
}