POST http://localhost:3000/usergroups/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE3MjQ0MTc1LCJleHAiOjE3MTcyODAxNzV9.DqGiMQYQzKVI2pCPuB2Kxb4LfPwKlb8OGoemYE7Lgds

{
  "userId" : 31,
  "groupId" : 5
}