POST http://localhost:3000/usergroups/
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiRGF2aWQiLCJpYXQiOjE3MTMzNDQ3NDMsImV4cCI6MTcxMzM0ODM0M30.2vKqUfI1iuF_u0eJfihrP-k-T_gy2g_RNg-2JTCAy2c

{
  "userId" : 10,
  "groupId" : 4
}