PUT http://localhost:3000/usergroups/quit-group/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6IlN0ZXBoIiwiaWF0IjoxNzE3MzM2MTk5LCJleHAiOjE3MTczNzIxOTl9.1a8_M1wVxPXFZJc8pZP_4BkyQV83ukZZUagisgancsY

{
    "userId": 31
}